package com.rouesnel.typedsql.examples
package coppersmith

import org.apache.hadoop.fs.Path
import com.twitter.scalding.{Config, Execution, TypedPipe}
import org.joda.time.DateTime
import commbank.coppersmith.api.{DataSource => _, _}
import scalding._
import Coppersmith._
import EavtText.{EavtEnc, eavtByDay}
import com.rouesnel.typedsql.SqlQuery
import com.rouesnel.typedsql.examples.coppersmith.TypedSqlCoppersmithExample.{Parameters, Sources}
import commbank.coppersmith.thrift.Eavt

import com.rouesnel.typedsql.DataSource


@SqlQuery object TypedSqlCoppersmithExample {

  def query =
    """
      SELECT c.customer_id     as customer_id,
             c.age             as age,
             COUNT(o.order_id) as number_of_orders,
             SUM(oli.item_discount * oli.item_quantity) as amount_discounted,
             SUM(oli.item_price * oli.item_quantity)    as gross_amount_spent
       FROM ${customers} c
         LEFT OUTER JOIN ${orders} o ON c.customer_id = o.customer_id
         LEFT OUTER JOIN ${orderLineItems} oli ON o.order_id = oli.order_id
       WHERE c.age > ${minimumAge}
       GROUP BY c.customer_id, c.age
    """

  case class Sources(customers: DataSource[Customer],
                     orders: DataSource[Order],
                     orderLineItems: DataSource[OrderLineItem],
                     payments: DataSource[Payment])

  case class Parameters(minimumAge: Int)


  object Features extends BasicFeatureSet[Row] {
    val namespace          = "typedsql.example"
    def entity(row: Row) = row.customerId.toString

    val customerAge = basicFeature[Integral](
      "CUSTOMER_AGE", "Age of customer in years", Continuous, Some(MinMaxRange[Integral](0, 130))
    )(row => row.age)

    val orderCount = basicFeature[Integral](
      "ORDER_COUNT", "Number of orders the customer has made.", Continuous
    )(row => row.numberOfOrders)

    val grossAmountSpent = basicFeature[Integral](
      "GROSS_AMOUNT_SPENT", "Amount spent by the customer (before discounts).", Continuous
    )(row => row.grossAmountSpent)

    val amountDiscounted = basicFeature[Integral](
      "MONEY_SAVED", "Amount of money saved by the customer due to discounts on ordered items.", Continuous
    )(row => row.amountDiscounted)

    val amountSpent = basicFeature[Integral](
      "NET_AMOUNT_SPENT", "Amount spent by the customer (reduced by any discounts). Also known as revenue generated by customer.", Continuous
    )(row => row.grossAmountSpent - row.amountDiscounted)

    val features = List(customerAge, orderCount, grossAmountSpent, amountDiscounted, amountSpent)
  }
}
